# Generated by Django 5.0.4 on 2024-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
