# Generated by Django 4.2.11 on 2024-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_emailmessagemodel_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessagemodel',
            name='snippet',
            field=models.TextField(blank=True, default=''),
        ),
    ]
