# Generated by Django 5.0.4 on 2024-05-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0002_customuser_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenmodel",
            name="access_token",
        ),
    ]
