# Generated by Django 5.0.4 on 2024-05-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0003_remove_tokenmodel_access_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenmodel",
            name="refresh_token",
        ),
        migrations.AddField(
            model_name="tokenmodel",
            name="google_refresh_token",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="tokenmodel",
            name="jwt_refresh_token",
            field=models.TextField(default=""),
        ),
    ]
