# Generated by Django 5.0.4 on 2024-05-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0004_remove_tokenmodel_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenmodel",
            name="google_access_token",
            field=models.TextField(default=""),
        ),
    ]
