# Generated by Django 4.2.11 on 2024-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_alter_emailmessagemodel_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessagemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='emailmessagemodel',
            index=models.Index(fields=['userid'], name='detector_em_userid__020b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessagemodel',
            index=models.Index(fields=['date'], name='detector_em_date_4749f7_idx'),
        ),
    ]
