# Generated by Django 5.0.4 on 2024-05-09 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0005_tokenmodel_google_access_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("header", models.CharField(default="", max_length=255)),
                ("body", models.TextField(default="")),
                ("date", models.DateTimeField()),
                ("sender", models.CharField(default="", max_length=255)),
                ("to", models.CharField(default="")),
                ("spam", models.BooleanField(default=False)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
