# Generated by Django 5.0.4 on 2024-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0006_emailmessagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessagemodel",
            name="message_id",
            field=models.BigIntegerField(default=None),
        ),
    ]
