# Generated by Django 5.0.4 on 2024-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0007_emailmessagemodel_message_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmessagemodel",
            old_name="spam",
            new_name="is_spam",
        ),
        migrations.RenameField(
            model_name="emailmessagemodel",
            old_name="userid",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="emailmessagemodel",
            name="message_id",
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
