# Generated by Django 5.0.4 on 2024-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0008_rename_spam_emailmessagemodel_is_spam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessagemodel",
            name="message_id",
            field=models.CharField(default=None, unique=True),
        ),
    ]
