# Generated by Django 5.0.4 on 2024-05-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0009_alter_emailmessagemodel_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailmessagemodel",
            name="user_id",
        ),
    ]
