# Generated by Django 5.0.4 on 2024-05-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0010_remove_emailmessagemodel_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmessagemodel",
            old_name="to",
            new_name="To",
        ),
        migrations.RenameField(
            model_name="emailmessagemodel",
            old_name="is_spam",
            new_name="spam",
        ),
    ]
