# Generated by Django 5.0.4 on 2024-05-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0012_emailmessagemodel_snippet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmessagemodel",
            old_name="To",
            new_name="recipient",
        ),
    ]
