# Generated by Django 4.2.11 on 2024-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0013_rename_to_emailmessagemodel_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessagemodel",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
    ]
