# Generated by Django 4.2.11 on 2024-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0014_alter_emailmessagemodel_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessagemodel",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
